//
//  ItemDetailsPresenter.swift
//  InternetShop
//
//  Created by Алексей Колыченков on 24.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ItemDetailsPresentationLogic {
    func presentItemDetails (response: ItemDetails.ShowDetails.Response)
}

class ItemDetailsPresenter: ItemDetailsPresentationLogic {
    weak var viewController: ItemDetailsDisplayLogic?


    func presentItemDetails (response: ItemDetails.ShowDetails.Response) {
        let itemPrice = "\(response.price ?? 0)$"

        let viewModel = ItemDetails.ShowDetails.ViewModel(title: response.title ?? "",
                                                          price: itemPrice,
                                                          description: response.description ?? "",
                                                          category: response.category ?? .mensClothing,
                                                          imageURL: response.imageURL!)

        viewController?.displayShowDetails(viewModel: viewModel)
    }
}
