//
//  ItemDetailsInteractor.swift
//  InternetShop
//
//  Created by Алексей Колыченков on 24.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ItemDetailsBusinessLogic {
    func provideItemDetails(request: RequestDetail)
}

protocol ItemDetailsDataStore {
    var item: MenuItem? { get set }
}

class ItemDetailsInteractor: ItemDetailsBusinessLogic, ItemDetailsDataStore {
    var item: MenuItem?
    var presenter: ItemDetailsPresentationLogic?
    var worker: ItemDetailsWorker?


    func provideItemDetails(request: RequestDetail) {
        switch request {
        case .getDetails:
            let response = ItemDetails.ShowDetails.Response(title: item?.title,
                                                            price: item?.price,
                                                            description: item?.description,
                                                            category: item?.category,
                                                            imageURL: item?.image)

            presenter?.presentItemDetails(response: response)
        }
    }
}
