//
//  ItemDetailsInteractor.swift
//  InternetShop
//
//  Created by Алексей Колыченков on 24.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ItemDetailsBusinessLogic {
    func doShowDetails(request: ItemDetails.ShowDetails.Request.RequestType)
}

protocol ItemDetailsDataStore {
    var item: MenuItem? { get set }
}

class ItemDetailsInteractor: ItemDetailsBusinessLogic, ItemDetailsDataStore {
    var item: MenuItem?
    var presenter: ItemDetailsPresentationLogic?
    var worker: ItemDetailsWorker?
    private var fetcher: DataFetcher = NetworkDataFetcher(networking: NetworkManager())


    // MARK: Do ShowDetails
    func doShowDetails(request: ItemDetails.ShowDetails.Request.RequestType) {
        worker = ItemDetailsWorker()

        switch request {
        case .getDetails:
            fetcher.getData { response in
                guard let response = response else { return }
                presenter?.presentShowDetails(response: response)
            }
        }
    }
}
