//
//  ItemDetailsPresenter.swift
//  InternetShop
//
//  Created by Алексей Колыченков on 24.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailsPresentationLogic {
    func presentShowDetails (response: ItemDetails.ShowDetails.Response.ResponseType)
}

class ItemDetailsPresenter: ItemDetailsPresentationLogic {
    weak var viewController: ItemDetailsDisplayLogic?

    // MARK: Do ShowDetails

    func presentShowDetails (response: ItemDetails.ShowDetails.Response.ResponseType) {
        switch response {
        case .presentDetails(let response):
            let itemPrice = "от \(response ?? 0)$"
        }
        let viewModel = ItemDetails.ShowDetails.ViewModel.ViewModelData.displayMenu(menuViewModel: response)
        viewController?.displayShowDetails (viewModel: viewModel)
    }
}
