//
//  ItemDetailsModels.swift
//  InternetShop
//
//  Created by Алексей Колыченков on 24.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias RequestDetail = ItemDetails.ShowDetails.Request.RequestType

enum ItemDetails {
    enum ShowDetails  {
        
        struct Request {
            enum RequestType {
                case getDetails
            }
        }

        struct Response {
            let title: String?
            let price: Double?
            let description: String?
            let category: Category?
            let imageURL: String?
        }

        struct ViewModel {
            let title: String
            let price: String
            let description: String
            let category: Category
            let imageURL: String
        }
    }
}
